######################
# plakar-backup.conf #
######################

### DESTINATIONS ###

# LOCAL1 - disque local monté en permanence
LOCAL1_PATH="/media/BACKUP"

# LOCAL2 - disque USB préalablement monté
LOCAL2_PATH="/media/USB"

# NFS
# Exemple fstab : 192.168.21.252:/bkp/superlinux /mnt/nfs nfs rw,noauto,user 0 0
NFS_MOUNT_SRC="192.168.21.252:/bkp/superlinux"
NFS_MOUNT_POINT="/mnt/nfs"

# SSH via sshfs
SSH_MOUNT_SRC="adrien@192.168.21.252:/bkp/superlinux"
SSH_MOUNT_POINT="/mnt/ssh"
SSH_OPTIONS="-o port=22"

### SOURCES ###
# Laisser SOURCE_PATH vide pour désactiver la source

SOURCE1_PATH="/media/DATA"
SOURCE1_REPO="DATA"

SOURCE2_PATH="/home/adrien"
SOURCE2_REPO="HOME"

SOURCE3_PATH=""
SOURCE3_REPO=""

SOURCE4_PATH=""
SOURCE4_REPO=""

SOURCE5_PATH=""
SOURCE5_REPO=""

### COMMUN ###
EXCLUDE_FILE="/media/DATA/plakar-exclude.list"

### RÉTENTION (statique) ###
PRUNE_OPTS="-days 7 -per-day 1 -weeks 4 -per-week 1 -months 10 -per-month 1"

### RESTAURATION ###
RESTORE_PATH=~/plakar-restore/
