[llm]
# URL de base du serveur llama.cpp (compatible OpenAI)
base_url = http://localhost:8080/v1

# Clé API (inutile sur un inférence locale)
api_key = sk-no-key-required

# Nom du modèle (facultatif si llamacpp ou vLLM, masis nécessaire pour ollama)
model = qwen3.5

# Nombre maximum de tokens
max_tokens = 16000

# Température
temperature = 0.7

[agent]
# Prompt système 
system_prompt = Tu es un agent expert. Utilise tes outils pour donner des réponses précises et bien structurées.

[tools]
# Active ou désactive chaque outil individuellement (true / false)
enable_meteo  = true
enable_wiki   = true
enable_argent = true

[web]
# Titre affiché dans l'onglet du navigateur
page_title = Chat LLM Linuxtricks avec Outils
# Emoji dans la barre de titre
page_icon  = 🤖
# Titre H1 de l'interface Streamlit
header     = Chat LLM Linuxtricks avec Outils

[cli]
# Bannière d'accueil au démarrage
banner       = === AGENT PRÊT — Tapez 'exit' pour quitter ===
# Préfixes d'affichage dans la console
user_prefix  = Vous
agent_prefix = Agent
