[DEFAULT]
# API a utiliser (2 exemples en dessous)
# API_BASE = http://localhost:11434/v1    # Ollama
# API_BASE = http://localhost:8000/v1     # vLLM
API_BASE = http://192.168.21.144:11434/v1

# Le nom du modèle.
# Note : avec vLLM ou llama-server, ce paramètre est ignoré côté serveur 
# car il sert le modèle préchargé, mais il est requis dans le payload.
#MODEL_NAME = gemma3:4b # Exemple Ollama
#MODEL_NAME = openai/gpt-oss-20b # Exemple VLLM
MODEL_NAME = gemma3:4b

SYSTEM_PROMPT = Tu es un assistant utile, clair et concis.

MAX_HISTORY = 10
